inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/internal/**/*'
    - 'spec/test_app_templates/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/spotlight/dor/indexer.rb'
