inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - '.internal_test_app/**/*'
    - 'spec/test_app_templates/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 130

Style/ClassAndModuleChildren:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/*'

RSpec/FilePath:
  Enabled: false
