notifications:
  email: false

rvm:
  - 2.3.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RAILS_VERSION=4.2.6

sudo: false
language: ruby

script:
  - bundle exec rake

jdk: oraclejdk8
